"""Pydantic models for structured LLM outputs.

These are used with ``services.llm.chat_json`` to enforce schema-validated
responses from the language model.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Feature proposals
# ---------------------------------------------------------------------------


class FeatureProposal(BaseModel):
    """A single user-facing feature identified by the LLM."""

    id: str = Field(..., description="URL-safe slug, e.g. 'user-authentication'")
    title: str = Field(..., description="Short, user-facing title")
    description: str = Field(..., description="1-3 sentence user-facing description")
    seed_paths: list[str] = Field(
        default_factory=list,
        description="Repo-relative file paths most relevant to this feature",
    )


class FeatureProposalList(BaseModel):
    """Wrapper around a list of feature proposals."""

    features: list[FeatureProposal]


# ---------------------------------------------------------------------------
# Evidence selection
# ---------------------------------------------------------------------------


class EvidenceSelection(BaseModel):
    """LLM-selected chunk IDs relevant to a feature."""

    selected_chunk_ids: list[str] = Field(
        ...,
        description="chunk_ids (path:start-end) selected as relevant evidence",
    )
    rationale: str = Field(
        ...,
        description="Brief explanation of why these chunks were selected",
    )


# ---------------------------------------------------------------------------
# Wiki page draft
# ---------------------------------------------------------------------------


class WikiPageDraft(BaseModel):
    """A single wiki page generated by the LLM."""

    title: str = Field(..., description="Page title")
    content_md: str = Field(
        ...,
        description=(
            "Full markdown content. Inline citations use [path:start-end] format."
        ),
    )
